DROP DATABASE IF EXISTS `A2024`;
CREATE DATABASE `A2024`;
USE `A2024`;


CREATE TABLE Users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    level int NOT NULL
) ENGINE = InnoDB;